# Generated by Django 5.2.6 on 2025-09-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_studentprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
